### ISSUE TITLE
ts_defs not included in npm package

### ISSUE THREAD

**Issue by jefbarn** [DevExpress/testcafe-angular-selectors#14]
Hi, awesome that this is including typescript definitions. However it appears the ts_defs directory is not being added to the npm distribution.

Appears the fix is to add 
```
 "files": [
    "lib",
    "ts-defs"
  ],
```
to package.json

**Comment by pmccaughtry** [comment]
Hi. I am running version 0.3.2 and this issue just started happening to me after 5 days of successful test runs. I have verified package.json has the updates in eeaea79 but still receive: Error: Cannot find module 'testcafe-angular-selectors/ts-defs/index'

As mentioned, this is new and the version of testcafe-angular-selectors hasn't changed. To troubleshoot I have uninstalled and reinstalled twice with no luck. It doesn't appear that compilation of the ts file is happening. I am running the tests on a macbook pro.

Please advise.

Thank you

**Comment by jefbarn** [comment]
@pmccaughtry 
I've seen errors like this if I have a different tsconfig in my tests folder and my editor doesn't resolve the node_modules correctly.
Also you could try ```npm list testcafe-angular-selectors``` to verify the correct version is installed.

**Comment by pmccaughtry** [comment]
Thanks for the quick response. I looked deeper into the errors and noticed that my IDE added some funky imports linking to the index page. Once I removed the import statements, the problem went away.
