### ISSUE TITLE
Object returned by getAngular() function has invalid type

### ISSUE THREAD

**Issue by RafalOsieka** [DevExpress/testcafe-angular-selectors#22]
# bug report

### description

The object returned by `AngularSelector().getAngular()` (without parameter) has invalid type.

### problem analysis

```typescript
import { Selector, ClientFunction } from 'testcafe';

interface Dictionary {
    [name: string]: any;
}

export type State = object | Dictionary;

export type AngularComponent<
    S extends State = {},
    > = {
        state: S,
    };

type DefaultAngularComponent = AngularComponent<State>;

declare global {
    type AngularComponent<
        S extends State = {},
        > = {
            state: S,
        };
    interface Selector {
        getAngular<C extends DefaultAngularComponent = DefaultAngularComponent>(): Promise<C>;
        getAngular<C extends DefaultAngularComponent = DefaultAngularComponent, T = any>(filter?: (angularInternal: C) => T): Promise<T>;
    }
}
```

As you can see in the code above (src: `index.d.ts`), the `getAngular()` function returns `Promise<C>`, where C by default resolves to `AngularComponent<S>` which resolves to object:
```typescript
{
  state: S
}
```

But, the `getAngular` implementation returns the state value, instead the object with the state property.
`angular-selector.js` file:
```typescript
...
if (typeof fn === 'function')
  return fn({ state });

return state;
```

#### solution 1
in the `getAngular` function instead of `return state;` should be `return {state};`

#### solution 2
update the typings for `getAngular` function. Should be something like `getAngular<C extends AngularComponent<State>>(): Promise<State>;`

### Anything else relevant?
The `getAngular` function with filter parameter is working fine.

**Comment by Ogurecher** [comment]
@zepa19, Thank you for your report. The typings for the `getAngular` function should be updated. If you are interested, feel free to contribute.
