### ISSUE TITLE
Update the tested Angular application to the latest stable version

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-angular-selectors#7]

**Comment by Hotell** [comment]
some more context:

- test fail on `waitForAngular()` execution

- test:
```ts
import { waitForAngular } from 'testcafe-angular-selectors';

import { AppPage } from './app.po';

const page = new AppPage();

fixture('ro-sa App').beforeEach(async (t) => {
  await waitForAngular();
});

test('should display welcome message', async (t) => {
  await page.navigateTo();

  const paragraphText = await page.getParagraphText();

  await t.expect(paragraphText).contains('Welcome to app!');
});
```

command which executes tests:

```sh
testcafe chrome e2e/**/*.e2e-spec.ts --app 'ng serve' --app-init-delay 4000
```

![image](https://user-images.githubusercontent.com/1223799/36152875-cc393aec-110f-11e8-9a42-96d2faedeeae.png)

**Comment by doronsever** [comment]
Any news on this? 
Is testcafe ready for using Angular(6)?

**Comment by miherlosev** [comment]
Hi @doronsever 
 
>Any news on this?
 

We run tests only with [Angular 4](https://github.com/DevExpress/testcafe-angular-selectors/blob/master/package.json#L33).
I have not checked whether Angular 6 is supported.
I suggest you check this and let us know your results.
 
>Is testcafe ready for using Angular(6)?
 

Yes, you can use `TestCafe` for testing applications written with `Angular6` as well.

**Comment by davidgerrard** [comment]
I am seeing the same ' Error: Cannot find Angular in development mode.' message using Angular 6.0.3.

**Comment by jelling** [comment]
Are there any plans to resume support of this library? Angular 5 has been replaced by Angular 6 and Angular 7 is on the way. It would be a big help to a lot of Angular developers *cough* possible customers *cough* if support was resumed. Protractor is the default e2e solution that ships with Angular but it's just okay and has all of the problems of other Selenium based e2e frameworks.

**Comment by jelling** [comment]
On second thought, this may not be necessary anymore. With reactive forms you can get a field based on it's formControl like this:

```
.typeText(Selector("input").withAttribute("formcontrolname","email"), "some string")
```

**Comment by npavangouda** [comment]
@miherlosev  Even I am getting Error: Cannot find Angular in development mode. My application is angular 7.
Is testcafe supporting angular 7 apps.
@jelling did you find any work around for this issue?

**Comment by jelling** [comment]
@npavangouda what are you trying to accomplish? I don't think the helper library is necessary anymore for most things. For example, here's a helper function I wrote for selecting and filling text fields based on their formControlName:

```
import { Selector } from "testcafe";
import { ClientFunction } from "testcafe";

export function f(formControlName: string, type: string = "input") {
    return Selector(type).withAttribute(/formcontrolname/i, formControlName);
}
```

**Comment by kildareflare** [comment]
I have the same issue.
I've just started experimenting with testcafe and have this very simple test.
But it fails with **Error: Cannot find Angular in development mode**

```
import { Selector } from 'testcafe';
import { waitForAngular } from 'testcafe-angular-selectors';

fixture('Node Login')
  .page('http://localhost:4200')
  .beforeEach(async () => {
    await waitForAngular();
  });

test('Test Login Title', async t => {
  const title = Selector('h2');
  await t.expect(title.innerText).eql('Login');
});
```

Which I trigger using a script defined in the package.json
`"testCafe": "testcafe chrome ./src/e2e/ --app \"npm run start\""`

Testcafe starts, opens the browser and connects.
I then see a blank screen for a few seconds before the test fails and the browser closes.
The following errors are in the console.

```
 1) - Error in fixture.beforeEach hook -
      Failed to find a DNS-record for the resource at
      "http://localhost:4200/".

      Browser: Chrome 71.0.3578 / Windows 10.0.0


   2) - Error in fixture.beforeEach hook -
      An error occurred in ClientFunction code:

      Error: Cannot find Angular in development mode.

      Browser: Chrome 71.0.3578 / Windows 10.0.0

          2 |import { waitForAngular } from 'testcafe-angular-selectors';
          3 |
          4 |fixture('Node Login')
          5 |  .page('http://localhost:4200')
          6 |  .beforeEach(async () => {
       >  7 |    await waitForAngular();
          8 |  });
          9 |
         10 |test('Test Login Title', async t => {
         11 |  const title = Selector('h2');
         12 |

```
I'll look into creating a small Angular App that replicates.

**Comment by shekhar-aspl** [comment]
@jelling, yes you are correct. No need of test_angular_selector now.

**Comment by antony-chiossi** [comment]
```
import { AngularSelector, waitForAngular } from 'testcafe-angular-selectors';

fixture `App tests`
  .page('http://localhost:4200')
  .beforeEach(async () => {
    await waitForAngular(30000);
  });

test('test', async t => {
  const firstListItem = AngularSelector('title');
  console.log(firstListItem);
});
```

by running this simple code `testcafe chrome src/test/testcafe/login.ts` i get:

```
Using locally installed version of TestCafe.
 Running tests in:
 - Chrome 72.0.3626 / Linux 0.0.0

 App tests
 ✖ test

   1) - Error in fixture.beforeEach hook -
      An error occurred in ClientFunction code:

      Error: Cannot find Angular in development mode.

      Browser: Chrome 72.0.3626 / Linux 0.0.0

          9 |import { AngularSelector, waitForAngular } from 'testcafe-angular-selectors';
         10 |
         11 |fixture `App tests`
         12 |  .page('http://localhost:4200')
         13 |  .beforeEach(async () => {
       > 14 |    await waitForAngular(30000);
         15 |  });
         16 |
         17 |test('test', async t => {
         18 |  const firstListItem = AngularSelector('title');
         19 |  console.log(firstListItem);


```


@miherlosev any news about this?

`ng -v` : 

> Angular CLI: 1.7.4
> Node: 10.15.3
> OS: linux x64
> Angular: 5.2.10
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 

> @angular/cli: 1.7.4
> @angular-devkit/build-optimizer: 0.3.2
> @angular-devkit/core: 0.3.2
> @angular-devkit/schematics: 0.3.2
> @ngtools/json-schema: 1.2.0
> @ngtools/webpack: 1.10.2
> @schematics/angular: 0.3.2
> @schematics/package-update: 0.3.2
> typescript: 2.5.3
> webpack: 3.11.0

**Comment by miherlosev** [comment]
I will investigate the compatibility with Angular 5+ in the nearest time.

**Comment by miherlosev** [comment]
Guys,

I've checked the `testcafe-angular-selectors` package with the application written with the latest Angular version (`7.2.9`). I've created this application using the [official Angular tutorial](https://angular.io/guide/quickstart).

All works as expected.
This is my test code and test execution report:

*test.js*
```js
import { AngularSelector, waitForAngular } from 'testcafe-angular-selectors';

fixture `Fixture`
    .page('http://localhost:4200/')
    .beforeEach(async () => {
        await waitForAngular();
    });

test('Test', async t => {
    const component = AngularSelector('app-root');
	
	console.log(await component.getAngular());
});
```

*test report*
![image](https://user-images.githubusercontent.com/4133518/54278162-b417fc00-45a2-11e9-85c5-3adf8d0bf716.png)

The `Error: Cannot find Angular in development mode.` message  means that you application is improperly prepared for testing. You can use `testcafe-angular-selectors` only with an application compiled in development mode (read [this](https://angular.io/guide/deployment#enable-runtime-production-mode) Angular's help topic for more detail).

I will also rename the issue to `Update the tested Angular application to the latest stable version` since this title is more suitable in this case.

**Comment by bvklingeren** [comment]
I'm suspecting that Angular 9 which is released today is not supported. Our tests started to fail after upgrading from Angular 8 to Angular 9 with the message `Error: Cannot find Angular in development mode.` and I'm sure we're running in development mode as we did with Angular 8.

After some initial investigation it seems that Angular 9 does not provide a `probe()` function on `window.ng` any more.
I have been toying a little in the browser console and it seems that I can get to a injector in the root element:
```
var elements = window.getAllAngularRootElements();
var comp = window.ng.getComponent(elements[0]);
comp.__ngContext__.debug.injector
```
However I'm not sure if this means that Angular is 'ready'.

I used this article as a reference: https://juristr.com/blog/2019/09/debugging-angular-ivy-console/

**Comment by miherlosev** [comment]
Hi @bvklingeren 

Thank you for the provided information. We will consider adding support for Angular 9 in the next development sprint.

**Comment by enten** [comment]
@miherlosev 
I opened a PR to add support for Angular 9.

**Comment by AlexSkorkin** [comment]
Thank you. We will look into it.
