### ISSUE TITLE
AngularSelector getAngular() not working

### ISSUE THREAD

**Issue by derchirurg** [DevExpress/testcafe-angular-selectors#8]
I cannot use .getAngular() to retrieve the angular component. I am getting the following error:

> getAngular cannot return DOM elements. Use Selector functions for this purpose.

I'm using ist with:
`const myComponentSelector = AngularSelector("app-mycomponent");`
`const myComponent = await myComponentSelector.getAngular();`

I am using Angular 5.2.0

**Comment by miherlosev** [comment]
Hi @derchirurg 

Could you please provide a small example to reproduce?

**Comment by derchirurg** [comment]
I don't know how to provide an online example, because I need Node to run the test.
Here is my test code:

```
import { Selector } from 'testcafe';
import { waitForAngular, AngularSelector } from 'testcafe-angular-selectors';

fixture("MyComponent").page("http://localhost:4200").beforeEach(async () => { await waitForAngular(); });

test("Default_NOK", async t =>
{
    const dataString = '{"name": "doe", "firstname": "john"}';
    const data = JSON.parse(dataString);
    const myComponentSelector = AngularSelector("app-mycomponent");
    const myComponent = await myComponentSelector.getAngular();
    myComponent.loadData(data);
});
```

My Component is:
```
import { Component, OnInit} from '@angular/core';

@Component({
    selector: 'app-mycomponent',
    templateUrl: './my.component.html',
    styleUrls: ['./my.component.scss']
})
export class MyComponent implements OnInit
{
    private data;
    
    constructor() 
    {
    }

    async ngOnInit()
    {
    }

    loadData(data)
	{
		this.data = data;
	}
}
```
I need to load Data in the component.

**Comment by miherlosev** [comment]
Could you please attach your example to this issue?

**Comment by d-amit** [comment]
Any updates or work around for this issue?

**Comment by AlexKamaev** [comment]
@d-amit,
We did not get the working project to reproduce the issue on our side. We will really appreciate it if you share your sample project with us.
